#!/bin/bash

echo alias userGenerate='source ./createuser' >> ~/.bashrc
echo alias permit='source ./permission' >> ~/.bashrc
echo alias autoSchedule='source ./sch' >> ~/.bashrc
echo alias attendance='source ./attd' >> ~/.bashrc
echo alias record='source ./rcd' >> ~/.bashrc
echo alias finalattendance='source ./fattd' >> ~/.bashrc
echo alias nearest='source ./near' >> ~/.bashrc

source ~/.bashrc
echo Aliases created
