#!/bin/bash

#permission for army general, navy marhsal and airforce chief
for i in {1..50}
do 
        setfacl -m u:ArmyGeneral:rwx -R /home/Army$i
        setfacl -m u:NavyMarshal:rwx -R /home/Navy$i
        setfacl -m u:AirForceCheif:rwx -R /home/AirForce$i
done

#permissions for cheif commander
setfacl -m u:CheifCommander:rwx -R /home/ArmyGeneral
setfacl -m u:CheifCommander:rwx -R /home/NavyMarshal
setfacl -m u:CheifCommander:rwx -R /home/AirForceCheif
for j in {1..50}
do
        setfacl -m u:CheifCommander:rwx -R /home/Army$j
        setfacl -m u:CheifCommander:rwx -R /home/Navy$j
        setfacl -m u:CheifCommander:rwx -R /home/AirForce$j
done

for k in {1..50}
do
        chmod o-rx /home/Army$k
        chmod o-rx /home/Navy$k
        chmod o-rx /home/AirForce$k
done
