#!/bin/bash

read -p "Enter your fleet: " fleet
read -p "Enter: " record day

#only 7 days in a week
if [ $day -ge 1 ] && [ $day -le 7 ]
then
        let "dayofweek = 14 - $day"
        matchitem=$(date --date="$dayofweek days ago" "+%Y-%m-%d")
        echo "Attendace record for $fleet on  $matchitem"
        echo "===================================="

        output=$(cat attendance | grep "^+$matchitem" | grep "$fleet"| cut -d " " -f 2,3 | column -t)
        echo -e "$output\n"
else
        echo Invalid input
fi


echo Done

